
jobs:
- name: job-docker-cf
  public: true
  serial: true
  plan:
  - aggregate:
    - get: docker-cf
      resource: git-docker-cf
      trigger: true
    - get: cf-cli-release
      resource: cf-cli-github-release
      trigger: true
  - task: get-cf-cli
    file: docker-cf/ci/build.yml
  - put: docker-cf-image
    params:
      build: get-cf-cli
      tag: cf-cli-release/version
      tag_prefix: v

resources:
- name: cf-cli-github-release
  type: github-release
  source:
    user: cloudfoundry
    repository: cli
    access_token: {{github-access-token}}

- name: git-docker-cf
  type: git
  source:
    uri: https://github.com/starkandwayne/docker-cf.git
    access_token: {{github-access-token}}

- name: docker-cf-image
  type: docker-image
  source:
    email: {{docker-hub-email}}
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}
    repository: starkandwayne/cf
